### PR TITLE
Fix for windows

### PR DESCRIPTION
**Pull request by syoyo**
First of all, thank you for sharing great tool!

These patches are requited to build lfptools on windows(also potentially required for some unix system).

### CODE REVIEW

**Comment by nrpatel** [comment]
Awesome!  Could you modify the Makefile to do the right thing on Windows/MinGW?

**Comment by syoyo** [comment]
Here you are,

https://github.com/syoyo/lfptools/commit/7fc3d956abe8c4f7e11149c280bce6296c904621

**Comment by syoyo** [comment]
FYI, I've coded simple lfp viewer with OpenGL. You might be interested in it. https://github.com/syoyo/lfptools/tree/master/glview

**Comment by tzafrir** [comment]
Great work syoyo!

I made small changes to compile this on Linux: https://github.com/tzafrir/lfptools/commit/148e1cb1cfeb19b413f0fca3c716913a5358bfd3

**Pull request merged**
